# Generated by Django 6.0.1 on 2026-05-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userotp_email_alter_userotp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
