# Generated by Django 6.0.1 on 2026-05-20 15:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_productmedia_file_alter_productmedia_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Elegance Redefined', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('tagline', models.CharField(blank=True, default='Premium Luxury Wigs', max_length=255)),
                ('cta_text', models.CharField(blank=True, default='Explore Collection', max_length=100)),
                ('cta_link', models.CharField(blank=True, default='/products', max_length=500)),
                ('secondary_cta_text', models.CharField(blank=True, default='Watch Our Story', max_length=100)),
                ('secondary_cta_link', models.CharField(blank=True, default='#', max_length=500)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('media_file', models.FileField(blank=True, help_text='Upload an image or video file from your device', null=True, upload_to='customization/hero/')),
                ('media_url', models.URLField(blank=True, help_text='Or provide an external URL for the media', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'db_table': 'customization_hero_slide',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('quote', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('media_file', models.FileField(blank=True, help_text='Upload a photo or video from your device', null=True, upload_to='customization/testimonials/')),
                ('media_url', models.URLField(blank=True, help_text='Or provide an external image/video URL', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'customization_testimonial',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('badge_text', models.CharField(blank=True, default='', max_length=100)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('media_file', models.FileField(blank=True, help_text='Upload an image from your device', null=True, upload_to='customization/featured/')),
                ('media_url', models.URLField(blank=True, help_text='Or provide an external image URL', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Featured Item',
                'verbose_name_plural': 'Featured Items',
                'db_table': 'customization_featured_item',
                'ordering': ['order', 'id'],
            },
        ),
    ]
