# Generated by Django 6.0.1 on 2026-05-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Affordable Hair and More', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('story_title', models.CharField(blank=True, default='Our Story', max_length=255)),
                ('story_content', models.TextField(blank=True, default='')),
                ('story_image', models.FileField(blank=True, help_text='Upload an image for the story section', null=True, upload_to='customization/about/')),
                ('story_image_url', models.URLField(blank=True, help_text='Or provide an external image URL', null=True)),
                ('mission_title', models.CharField(blank=True, default='Our Mission', max_length=255)),
                ('mission_content', models.TextField(blank=True, default='')),
                ('mission_image', models.FileField(blank=True, help_text='Upload an image for the mission section', null=True, upload_to='customization/about/')),
                ('mission_image_url', models.URLField(blank=True, help_text='Or provide an external image URL', null=True)),
                ('values', models.JSONField(blank=True, default=list, help_text='List of core values: [{"title": "...", "description": "..."}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
                'db_table': 'customization_about_page',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Get in Touch', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('working_hours', models.TextField(blank=True, default='')),
                ('social_links', models.JSONField(blank=True, default=list, help_text='Social media links: [{"platform": "Instagram", "url": "..."}]')),
                ('map_embed_url', models.TextField(blank=True, default='')),
                ('form_title', models.CharField(blank=True, default='Send Us a Message', max_length=255)),
                ('form_subtitle', models.TextField(blank=True, default='')),
                ('banner_image', models.FileField(blank=True, help_text='Upload a banner image', null=True, upload_to='customization/contact/')),
                ('banner_image_url', models.URLField(blank=True, help_text='Or provide an external banner image URL', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Pages',
                'db_table': 'customization_contact_page',
            },
        ),
    ]
