# Generated by Django 6.0.1 on 2026-05-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_aboutpage_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True, default='', help_text='Short snippet shown on the homepage')),
                ('content', models.TextField(blank=True, default='', help_text='Full blog post content')),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('product', 'Product Spotlight'), ('tips', 'Tips & Tricks'), ('beauty', 'Beauty & Style'), ('news', 'News & Updates'), ('general', 'General')], default='general', max_length=50)),
                ('cover_image_file', models.FileField(blank=True, help_text='Upload a cover image', null=True, upload_to='customization/blog/')),
                ('cover_image_url', models.URLField(blank=True, help_text='Or provide an external image URL', null=True)),
                ('read_time', models.CharField(blank=True, default='', help_text='e.g., "5 min read"', max_length=20)),
                ('external_link', models.URLField(blank=True, help_text='Link to full blog post (if hosted externally)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'customization_blog_post',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('how_to_use', 'How to Use'), ('care_tips', 'Care Tips'), ('styling', 'Styling Guide'), ('product_review', 'Product Review'), ('general', 'General')], default='general', max_length=50)),
                ('video_file', models.FileField(blank=True, help_text='Upload a video file from your device', null=True, upload_to='customization/videos/')),
                ('video_url', models.URLField(blank=True, help_text='Or provide an external video URL (YouTube, Vimeo, etc.)', null=True)),
                ('thumbnail_file', models.FileField(blank=True, help_text='Upload a thumbnail image for the video', null=True, upload_to='customization/video_thumbnails/')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Or provide an external thumbnail URL', null=True)),
                ('duration', models.CharField(blank=True, default='', help_text='e.g., "3:45"', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Content',
                'verbose_name_plural': 'Video Contents',
                'db_table': 'customization_video_content',
                'ordering': ['order', 'id'],
            },
        ),
    ]
