# Generated by Django 4.2.11 on 2026-05-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_account_name_payment_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='GHS', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='paystack', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('mobile_money', 'Mobile Money'), ('mtn_momo', 'MTN Mobile Money'), ('telecel_momo', 'Telecel Mobile Money'), ('airteltigo_momo', 'AirtelTigo Money'), ('bank_transfer', 'Bank Account Transfer')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference'], name='payments_pa_referen_75358f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
    ]
