# Generated by Django 4.2.11 on 2026-05-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
